chessassist/models.py
from chessassist import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return Users.query.get(int(user_id))

class Users(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String, unique=True)
    username = db.Column(db.String(200), nullable = False, unique=False)
    password_hash = db.Column(db.String(128))

    @property
    def password(self):
        raise AttributeError('Password is not a readable attribute.')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)
    
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

chessassist/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, EmailField, BooleanField, ValidationError
from wtforms.validators import DataRequired, Length, EqualTo

# Create a form classes

class UserForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired()])
    username = StringField('LiChess Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('password_2', message='Passwords must match.'), Length(min=8, message='Password must be at least 8 characters')])
    password_2 = PasswordField('Re-enter Password', validators=[DataRequired()])
    submit = SubmitField('Submit')

class LoginForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Submit')

chessassist/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from chessassist.config import Config

#extensions
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'users.login'

#app factory
def create_app(config_class=Config):

    app = Flask(__name__)

    app.config.from_object(Config)

    db.init_app(app)
    login_manager.init_app(app)

    from chessassist.main.routes import main
    from chessassist.users.routes import users

    app.register_blueprint(main)
    app.register_blueprint(users)

    return app

chessassist/main/routes.py
from flask import Blueprint, render_template

#blueprint instance
main = Blueprint('main', __name__)

#blueprint(main) routes
@main.route('/')
def index():
    return render_template('index.html')

@main.route('/about')
def about():
    return render_template('about.html')

chessassist/users/routes.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for
from chessassist.users.forms import UserForm, LoginForm
from chessassist import db
from werkzeug.security import generate_password_hash, check_password_hash
from chessassist.models import Users
from flask_login import login_user, login_required, logout_user, current_user
from chessassist.users.utils.make_lists import make_lists

#blueprint instance
users = Blueprint('users', __name__)

#blueprint(user) routes
@users.route('/create-account', methods=['GET', 'POST'])
def create_account():
    form = UserForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user is None:
            password_hash = generate_password_hash(form.password.data, 'sha256')
            user = Users(email=form.email.data, username=form.username.data, password_hash=password_hash)
            db.session.add(user)
            db.session.commit()
        form.email.data = ''
        form.username.data = ''
        form.password.data = ''
        form.password_2.data = ''
        flash('Account Creation Successful')
        return redirect(url_for('users.login'))
    return render_template('create_account.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user:
            if check_password_hash(user.password_hash, form.password.data):
                login_user(user)
                flash('Login Succesful')
                return redirect(url_for('users.profile'))
            else:
                flash("Wrong Password, Try Again")
        else:
            flash('No user associated with that email. Try again.')
    return render_template('login.html', form=form)

@users.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash('You have logged out.')
    return redirect(url_for('users.login'))


@users.route('/profile')
@login_required
def profile():
    missed_checkmates, opening_dict, missed_check_caps, games_your_blunders, games_their_blunders = make_lists(current_user.username)
    
    return render_template('user_profile.html', games_your_blunders=games_your_blunders, games_their_blunders=games_their_blunders, opening_dict = opening_dict, missed_checkmates=missed_checkmates, missed_check_caps=missed_check_caps)

@users.route('/test')
def test():
    return render_template('profile_test.html')

chessassist/templates/about.html
{% extends 'base.html'%}
{% block content %}
<div class="card" style="border-radius: 20px;">
    <div class="card-body">
      <h2 style="font-size: 20px;">Welcome to Chess Helper!</h2>
      <br>
      <p>This is a webapp to help you improve your chess game: <br> Create an account, view your favored openings, study positions from your own Lichess games, and more.</p>
        

    </div>
  </div>
{% endblock %}

chessassist/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Chess Helper</title>
  </head>
  <body>
    <h1 style='background-color: rgb(18, 117, 18); color: white; padding: 10px; padding-left: 30px; border-radius: 20px; margin-top: 5px; margin-left: 5px; margin-right: 5px; vertical-align: middle;'>Chess Helper</h1>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding: 10px; padding-left: 30px; border: solid 1px rgb(18, 117, 18); border-radius: 20px; margin-top: 5px; margin-left: 5px; margin-right: 5px;">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href='{{url_for("main.index")}}'>Home</a>
              <a class="nav-link" href='{{url_for("main.about")}}'>About</a>
              <a class="nav-link" href='{{url_for("users.create_account")}}'>Create Account</a>
              {% if current_user.is_authenticated %}
                <a class="nav-link" href='{{url_for("users.logout")}}'>Log Out</a>
              {% else %}
                <a class="nav-link" href='{{url_for("users.login")}}'>Log in</a>
              {% endif %}
              <a class="nav-link" href='{{url_for("users.profile")}}'>Profile</a>
            </div>
          </div>
        </div>
      </nav>
    <div class="container" style="margin-top: 30px;">

      {% for message in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{message}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}

      {% block content %}
      {% endblock %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

chessassist/templates/create_account.html
{% extends 'base.html'%}
{% block content %}

{% if username %}
    <h1>Hello {{ username }}</h1>
{% else %}
    <form method="POST">
        {{ form.hidden_tag() }}
        
        {{ form.email.label(class="form-label") }}
        {{ form.email(class="form-control") }}
        {{ form.username.label(class="form-label") }}
        {{ form.username(class="form-control") }}
        {{ form.password.label(class="form-label")}}
        {{ form.password(class="form-control")}}
        {{ form.password_2.label(class="form-label")}}
        {{ form.password_2(class="form-control")}}
        
        <br/>
        {{ form.submit(class="btn btn-success") }}

    
    </form>

{% endif %}
{% endblock %}

chessassist/templates/index.html
{% extends 'base.html'%}
{% block content %}
<div class="card" style="background-color: black; border-radius: 15px; width: 450px; margin-left: 10px; margin-top: 10px;">
    <iframe src="https://lichess.org/tv/frame?theme=brown&bg=dark" style="width: 400px; height: 444px; margin: auto;" allowtransparency="true" frameborder="0"></iframe>
</div>
{% endblock %}

chessassist/templates/login.html
{% extends 'base.html'%}
{% block content %}
<form method="POST">

    {{form.hidden_tag()}}

    {{ form.email.label(class="form-label") }}
    {{ form.email(class="form-control") }}
    {{ form.password.label(class="form-label")}}
    {{ form.password(class="form-control")}}
    <br/>
    {{ form.submit(class="btn btn-success") }}

</form>
{% endblock %}

chessassist/templates/user_profile.html
{% extends 'base.html'%}
{% block content %}
<div class="card">
  <div class="card-body" style="text-align:center;">
    Copy and paste a position from one of the lists below into your favorite board editor to practice.
  </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                  Positions before you blundered
                </button>
              </h2>
              <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    {% for game in games_your_blunders %}
                        <li class="list-group-item">{{game}}</li>
                    {% endfor %}
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  Positions after they blundered...Take advantage!
                </button>
              </h2>
              <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    {% for game in games_their_blunders %}
                        <li class="list-group-item">{{game}}</li>
                    {% endfor %}
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                  Last 50 games by opening W/D/L
                </button>
              </h2>
              <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  {% for opening in opening_dict %}
                  <li class="list-group-item">{{opening}} {{opening_dict[opening]}}</li>
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingFour">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                  Positions before missed checkmake sequences
                </button>
              </h2>
              <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  {% for game in missed_checkmates %}
                  <li class="list-group-item">{{game}}</li>
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingFive">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                  Missed check then capture sequences
                </button>
              </h2>
              <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  {% for game in missed_check_caps %}
                  <li class="list-group-item">{{game}}</li>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
    </div>
  </div>
{%endblock%}